version: '3.4'

services:
 multishop.orderdb:
  environment:
    - ACCEPT_EULA=N
    - MSSQL_SA_PASSWORD=123456aA*
  volumes:
    - sqlserver_orderdb_volume:/var/opt/mssql
  ports:
      - "1434:1433"
 multishop.identitydb:
  environment:
        - ACCEPT_EULA=N
        - MSSQL_SA_PASSWORD=123456aA*
  volumes:
        - sqlserver_identitydb_volume:/var/opt/mssql
  ports:
        - "1433:1433"
 multishop.cargodb:
  environment:
        - ACCEPT_EULA=N
        - MSSQL_SA_PASSWORD=123456aA*
  volumes:
        - sqlserver_cargodb_volume:/var/opt/mssql
  ports:
        - "1435:1433"
 multishop.basketdb:
  volumes:
      - redis_basketdb_volume:/data
  ports:
      - "6379:6379"
 multishop.elasticsearch:
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DkIedPPSCb
    networks:
      - es-multishop-net
    ports:
      - 9200:9200
    expose:
      - 9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
 multishop.kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://multishop.elasticsearch:9200
    expose:
      - 5601
    networks:
      - es-multishop-net
    depends_on:
      - multishop.elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
