version: '3.4'

services:
  multishop.orderdb:
    container_name: multishop.orderdb-container
    image: mcr.microsoft.com/mssql/server:latest
  multishop.identitydb:
    container_name: multishop.identitydb-container
    image: mcr.microsoft.com/mssql/server:latest
  multishop.cargodb:
    container_name: multishop.cargodb-container
    image: mcr.microsoft.com/mssql/server:latest
  multishop.basketdb:
    container_name: multishop.basketdb-container
    image: redis:latest
  multishop.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: multishop.elasticSearchDb-container
  multishop.kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: multishop.kibana-container
volumes:
  sqlserver_orderdb_volume:
  sqlserver_identitydb_volume:
  sqlserver_cargodb_volume:
  redis_basketdb_volume:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
networks:
  es-multishop-net:
    driver: bridge
